services:
  mongodb:
    image: mongo
    container_name: mongodb
    expose:
      - "27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./social_rest
    container_name: backend
    expose:
      - "8000"
    environment:
      MONGO_URL: mongodb://mongodb:27017/social
    depends_on:
      - mongodb
    command: npm start

  frontend:
    build:
      context: ./react_client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data: