version: "3.9"

services:
  mongodb:
    ports:
      - "27017:27017"

  backend:
    ports:
      - "8000:8000"
    volumes:
      - ./social_rest:/app
      - backend-node-modules:/app/node_modules
    command: npm run dev

  frontend:
    build:
      context: ./react_client
      dockerfile: Dockerfile.dev

    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"


    ports:
      - "3001:3000"
    volumes:
      - ./react_client:/app
      - frontend-node-modules:/app/node_modules
    command: npm start

volumes:
  backend-node-modules:
  frontend-node-modules: